---
- name: Install sdkman
  shell: curl -s "https://get.sdkman.io" | bash
  changed_when: false
  become: no

- name: Update sdkman
  shell: >-
    . $HOME/.sdkman/bin/sdkman-init.sh && sdk selfupdate
  changed_when: false
  become: no
