---
- name: Install zsh libs
  apt:
    name: zsh
    state: latest

- name: Clone fzf
  git:
    repo: "{{ fzf_git_repo }}"
    dest: "{{ fzf_target_dir }}"
    depth: "1"
    accept_hostkey: yes
  become: no

- name: Install fzf
  command: "{{ fzf_target_dir }}/install --all"
  changed_when: false
  become: no

- name: Clone Oh-My-Zsh repo
  git:
    repo: "{{ omzsh_git_repo }}"
    dest: "{{ omzsh_target_dir }}"
    depth: "1"
    accept_hostkey: yes
  become: no

- name: Set zsh as default shell
  user:
    name: "{{ username }}"
    shell: /bin/zsh

- name: Stat .zshrc
  stat:
    path: ~/.zshrc
  become: no
  register: stat_zshrc

- name: Backup existing .zshrc
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: ~/.zshrc.bak
  become: no
  when: stat_zshrc.stat.islnk is defined and not stat_zshrc.stat.islnk

- name: Symlink .zshrc
  file:
    src: "{{ ansiblefiles_location }}/roles/shell/files/zshrc"
    dest: ~/.zshrc
    state: link
  become: no

- name: Clone zsh-autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: "1"
    accept_hostkey: yes
  become: no

- name: Clone zsh-syntax-highlighting
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: "1"
    accept_hostkey: yes
  become: no

- name: Clone zsh-sdkman
  git:
    repo: "https://github.com/matthieusb/zsh-sdkman.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-sdkman"
    depth: "1"
    accept_hostkey: yes
  become: no
