---

ansiblefiles_sublime_settings_dir: "{{ ansiblefiles_location }}/roles/sublime/files/User"

sublime_config_dir: ~/.config/sublime-text-3
sublime_settings_dir: "{{ sublime_config_dir }}/Packages/User"