---

docker_ubuntu_codename: focal
docker_debian_codename: stretch
docker_apt_repo_dist: "{{ lookup('pipe','. /etc/os-release && [ \"$ID\" = \"debian\" ] && echo debian || echo ubuntu')}}"
docker_apt_repo_codename: "{{ lookup('pipe','. /etc/os-release && [ \"$ID\" = \"debian\" ] && echo {{ docker_debian_codename }} || echo {{ docker_ubuntu_codename }}')}}"
