---
- name: Clone NVM repo
  git:
    repo: "{{ nvm_git_repo }}"
    dest: "{{ nvm_target_dir }}"
    accept_hostkey: true

- name: Install Node.js
  shell: "source {{ nvm_init_script }} && nvm install node"
  args:
    executable: /bin/bash
  register: install_node_result
  changed_when: "'is already installed.' not in install_node_result.stderr"

- name: Set default node version to latest
  shell: "source {{ nvm_init_script }} && nvm alias default node"
  args:
    executable: /bin/bash
  changed_when: false

- name: Determine current Node version
  shell: "source {{ nvm_init_script }} && nvm current"
  register: current_node_version
  changed_when: false

- name: Install latest global npm packages
  shell: "source {{ nvm_init_script }} && npm install -g {{ item }}"
  with_items: "{{ npm_packages }}"
  changed_when: false
