---

- name: Add Nodesource apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add Nodesource repo
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_11.x {{ ubuntu_codename }} main"
    mode: 644
    state: present
    update_cache: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: latest

- name: Install latest global npm packages
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items: "{{ npm_packages }}"
