---
- name: Add Nodesource apt key
  shell: curl -fsSL "https://deb.nodesource.com/gpgkey/nodesource.gpg.key" | gpg --dearmor -o /etc/apt/keyrings/nodejs.gpg
  args:
    creates: /etc/apt/keyrings/nodejs.gpg

- name: Add Nodesource repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/nodejs.gpg] https://deb.nodesource.com/node_18.x {{ ubuntu_codename }} main"
    mode: 644
    state: present
    update_cache: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: latest

- name: Install latest global npm packages
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items: "{{ npm_packages }}"
