---

ansiblefiles_location: "{{ lookup('env', 'HOME') }}/.ansiblefiles"
tmp_files_dir: "{{ ansiblefiles_location }}/tmp"
tools_dir: ~/dev/tools

ubuntu_keyserver: hkp://keyserver.ubuntu.com:80

ubuntu_name: "{{ lookup('pipe','lsb_release -si')}}"
ubuntu_codename: "{{ lookup('pipe','. /etc/os-release && echo $UBUNTU_CODENAME')}}"

username: "{{ lookup('env', 'USER') }}"
