---
- name: Clone pyenv repo
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "~/.pyenv"
    depth: 1
    accept_hostkey: yes
  become: no

- name: Clone xxenv repo
  git:
    repo: https://github.com/momo-lab/xxenv-latest.git
    dest: "~/.pyenv/plugins/xxenv-latest"
    depth: 1
    accept_hostkey: yes
  become: no

- name: Ensure latest pip packages installed
  pip:
    name: "{{ pip_packages }}"
    state: latest
  become: no
