---

nvm_git_repo: https://github.com/creationix/nvm.git
nvm_target_dir: ~/.nvm
nvm_init_script: "{{ nvm_target_dir }}/nvm.sh"

npm_packages:
  - npm
  - nodemon
  - coffee-script
  - gulp-cli
  - grunt
  - mocha
  - webpack
  - bower
  - eslint
  - babel-eslint
  - eslint-plugin-react
  - react-native-cli
  - flow-bin
  - webpack-bundle-size-analyzer
  - ava
