---

atom_packages:
  - linter
  - linter-eslint
  - linter-ui-default
  - intentions
  - busy-signal
  - language-babel
  - platformio-ide-terminal
  - editorconfig
  - sort-lines
  - prettier-atom
  - atom-beautify
  - highlight-selected
  - autocomplete-paths
  - autocomplete-modules
  - autoclose-html
  - local-history
  - hyperclick
  - js-hyperclick
  - color-picker
  - tree-view-copy-relative-path
  - pigments
  - split-diff
