export ZSH=$HOME/.oh-my-zsh

export EDITOR=nano

skip_global_compinit=1
ZSH_THEME="robbyrussell"

DISABLE_UPDATE_PROMPT="true"
DISABLE_AUTO_UPDATE="true"
plugins=(git kubectl)

export PATH=$HOME/bin:/usr/local/bin:$PATH

source $ZSH/oh-my-zsh.sh

export PATH="$PATH:$HOME/.rvm/bin"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"

alias k="kubectl"

ansiblefiles() { cd ~/.ansiblefiles && ./ansiblefiles.sh "$@" || true && cd $OLDPWD ;}

# Docker
# Stop all containers
dks() { docker kill $(docker ps -q) "$@"; }
# Delete all containers
dkrm() { docker rm $(docker ps -a -q) "$@"; }
# Delete all images
dkrmi() { docker rmi $(docker images -q) "$@"; }

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/scavlev/.sdkman"
[[ -s "/home/scavlev/.sdkman/bin/sdkman-init.sh" ]] && source "/home/scavlev/.sdkman/bin/sdkman-init.sh"
