skip_global_compinit=1
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=250'

DISABLE_UPDATE_PROMPT=true
DISABLE_AUTO_UPDATE=true

export EDITOR=nano

plugins=(
  pyenv
  history
  sudo
  git
  git-extras
  zsh-autosuggestions
  zsh-syntax-highlighting
  aws
  encode64
  urltools
  extract
  httpie
  kubectl
  helm
  jsontools
  fzf
  zsh-sdkman
)

source $ZSH/oh-my-zsh.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH=$HOME/.local/bin:$HOME/bin:/usr/local/bin:$PATH
export PATH=$PATH:/usr/local/go/bin
export PATH="$PATH:$HOME/.rvm/bin"

ansiblefiles() { cd ~/.ansiblefiles && ./ansiblefiles.sh "$@" || true && cd $OLDPWD ;}

# Docker
# Stop all containers
dks() { docker kill $(docker ps -q) "$@"; }
# Delete all containers
dkrm() { docker rm $(docker ps -a -q) "$@"; }
# Delete all images
dkrmi() { docker rmi $(docker images -q) "$@"; }
