---
- name: Add Kubernetes apt key
  shell: curl -fsSL "https://packages.cloud.google.com/apt/doc/apt-key.gpg" | gpg --dearmor -o /etc/apt/keyrings/kubernetes.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes.gpg

- name: Add Kubernetes repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/kubernetes.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    mode: 644
    state: present
    update_cache: yes

- name: Install Kubernetes tools
  apt:
    name:
      - kubectl
      # - kubeadm
      # - kubernetes-cni
    state: latest

- include_tasks: helm.yml

- include_tasks: kns.yml

- include_tasks: ktx.yml

- include_tasks: k9s.yml

- include_tasks: kube-ps1.yml
