---
- name: Add Google Chrome apt key
  shell: curl -fsSL "https://dl-ssl.google.com/linux/linux_signing_key.pub" | gpg --dearmor -o /etc/apt/keyrings/chrome.gpg
  args:
    creates: /etc/apt/keyrings/chrome.gpg

- name: Add Google Chrome repo
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/chrome.gpg] https://dl.google.com/linux/chrome/deb/ stable main
    mode: 644
    filename: google-chrome
    state: present
    update_cache: yes

- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    state: latest
