---
- name: Add VirtualBox apt key
  shell: curl -fsSL "https://www.virtualbox.org/download/oracle_vbox_2016.asc" | gpg --dearmor -o /etc/apt/keyrings/virtualbox.gpg
  args:
    creates: /etc/apt/keyrings/virtualbox.gpg

- name: Add VirtualBox repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/virtualbox.gpg] https://download.virtualbox.org/virtualbox/debian {{ ubuntu_codename }} contrib"
    mode: 644
    state: present
    update_cache: yes

- name: Install VirtualBox
  apt:
    name: "virtualbox-{{ virtualbox_version }}"
    state: latest

- name: Install dkms
  apt:
    name: dkms
    state: latest
