---
- name: Get latest go version
  shell: curl https://go.dev/dl/ -s | grep -v -E 'go[0-9\.]+(beta|rc)' | grep -E -o 'go[0-9\.]+' | grep -E -o '[0-9]\.[0-9]+(\.[0-9]+)?' | sort -V | uniq | tail -1
  register: go_latest_version
  changed_when: false

- name: Download Go
  unarchive:
    src: https://go.dev/dl/go{{ go_latest_version.stdout }}.linux-amd64.tar.gz
    dest: /usr/local
    group: root
    remote_src: yes
