---

- name: Add Go apt key
  apt_key:
    keyserver: "{{ ubuntu_keyserver }}"
    id: 56A3D45E
    state: present

- name: Add Go repo
  apt_repository:
    repo: "deb http://ppa.launchpad.net/longsleep/golang-backports/ubuntu {{ ubuntu_codename }} main"
    mode: 644
    state: present
    update_cache: yes

- name: Install Go
  apt:
    name: golang-go
    state: latest
