---

- name: Get latest terraform version
  uri:
    url: https://checkpoint-api.hashicorp.com/v1/check/terraform
    method: GET
    status_code: 200
    timeout: 10
  register: terraform_release

- name: Extract terraform version
  set_fact:
    terraform_version: "{{ terraform_release.json | json_query('current_version') }}"

- name: Install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /usr/local/bin
    group: root
    remote_src: yes

- name: Get terragrunt url
  shell: curl -s https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | grep "browser_download_url.*linux_amd64" | cut -d '"' -f 4
  changed_when: false
  args:
    warn: no
  register: terragrunt_url

- name: Install terragrunt
  get_url:
    url: "{{ terragrunt_url.stdout }}"
    dest: /usr/local/bin/terragrunt
    force: yes
    mode: +x
