---
- name: Perform apt dist upgrade
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    cache_valid_time: 3600

- name: Install essential libs
  apt:
    name:
      - curl
      - wget
      - jq
      - software-properties-common
      - build-essential
      - httpie
      - htop
    state: latest

- name: Symlink itself to ~/.ansiblefiles
  file:
    src: "{{ playbook_dir }}"
    dest: "{{ ansiblefiles_location }}"
    state: link
    force: yes
  become: no
  when: "playbook_dir != ansiblefiles_location"

- name: Increase inotify limit
  lineinfile:
    dest: /etc/sysctl.conf
    line: fs.inotify.max_user_watches=524288
