---
- name: Add Docker apt key
  apt_key:
    keyserver: hkp://pgp.mit.edu:80
    id: 0EBFCD88
    state: present

- name: Add Docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ docker_apt_repo_dist }} {{ docker_apt_repo_codename }} stable"
    mode: 644
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-compose
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Add user to docker group
  user:
    name: "{{ item }}"
    groups:
      - docker
    append: yes
  with_items:
    - "{{ username }}"
