---

- name: Install latest Java
  shell: >-
    . $HOME/.sdkman/bin/sdkman-init.sh && sdk install java
  register: jdk_install_result
  failed_when: jdk_install_result.rc > 1 # fails on the same version install with rc = 1
  changed_when: false
  become: no