---

- name: Download visualvm
  get_url:
    url: "{{ visualvm_url }}"
    dest: "{{ visualvm_archive }}"
  register: visualvm_download

- name: Extract visualvm
  unarchive:
    src: "{{ visualvm_archive }}"
    dest: /opt

- name: Symlink visualvm
  file:
    src: /opt/visualvm_{{ visualvm_version | regex_replace('\.') }}/bin/visualvm
    dest: "/usr/local/bin/visualvm"
    state: link
  become: yes
