---
- name: Add Waypoint apt key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add Waypoint repo
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ubuntu_codename }} main"
    mode: 644
    state: present
    update_cache: yes

- name: Install Waypoint
  apt:
    name: waypoint
    state: latest
