---
- name: Add Waypoint apt key
  shell: curl -fsSL "https://apt.releases.hashicorp.com/gpg" | gpg --dearmor -o /etc/apt/keyrings/waypoint.gpg
  args:
    creates: /etc/apt/keyrings/waypoint.gpg

- name: Add Waypoint repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/waypoint.gpg] https://apt.releases.hashicorp.com {{ ubuntu_codename }} main"
    mode: 644
    state: present
    update_cache: yes

- name: Install Waypoint
  apt:
    name: waypoint
    state: latest
